GET http://localhost:3001/confessions

###

POST http://localhost:3001/confession/new
Content-Type: application/json

{
    "text": "bread"
}

###


DELETE http://localhost:3001/confession/delete/61ce864622a57667a508d45c


###

PUT http://localhost:3001/confession/complete/